- name: Prefer Binary Packages
  hosts: all

  vars:
    path: /etc/portage/make.conf

  tasks:
  - name: Add block if heading not present
    blockinfile:
      path: '{{path}}'
      state: present
      marker: '# {{ansible_play_name}} {mark}'
      block: |
        FEATURES="getbinpkg"
        # Require that all binpkgs be signed and reject them if they are not (or have an invalid sig)
        FEATURES="binpkg-request-signature"
      #prepend_newline: yes #enable this when updated

